### ISSUE TITLE
Segmentation fault on exit in Timer destructor

### ISSUE THREAD

**Issue by akien-mga** [YuriSizov/boscaceoil-blue#4]
- boscaeceoil-blue version: https://github.com/YuriSizov/boscaceoil-blue/commit/d578cc46ed7fbb914caa52f1d3af2dfa0c33c486
- gdsion version: https://github.com/YuriSizov/gdsion/commit/0a3cc4dc2b8c41742734c0eda37149eaca7a4bec
- godot version: https://github.com/godotengine/godot/commit/e001bc75e8b9395186579e49620764fd05a2f97a
- OS: Fedora 40, compiled with GCC 14

---

When testing boscaceoil-blue with self-compiled gdsion and latest upstream Godot, I get a segfault on exit (just running the project, not doing anything and quitting with the `X` window button triggers it).

The stacktrace isn't super helpful:
```
(gdb) bt
#0  0x00007fffdea5df4b in ?? ()
#1  0x000000000aad035c in Object::~Object (this=0xb276090, __in_chrg=<optimized out>) at ./core/object/object.cpp:2145
#2  0x000000000a528ff1 in Time::~Time (this=0xb276090, __in_chrg=<optimized out>) at ./core/os/time.cpp:450
#3  0x000000000a4d1ca8 in memdelete<Time> (p_class=0xb276090) at ./core/os/memory.h:116
#4  0x000000000a484f36 in unregister_core_types () at ./core/register_core_types.cpp:441
#5  0x0000000005b7255c in Main::cleanup (p_force=false) at main/main.cpp:4317
#6  0x0000000005ab37d1 in main (argc=1, argv=0x7fffffffd728) at platform/linuxbsd/godot_linuxbsd.cpp:89
```

I'm using `dev_build`s for both Godot and GDSiON but can't seem to get more details from gdb. I'm not sure if it's not able to load debug symbols from the shared library or if it's something else.

Might very well be a Godot or godot-cpp bug, but starting with a downstream report until we can assess where the crash comes from.

**Comment by akien-mga** [comment]
Yeah I could reproduce this upstream with:
```diff
diff --git a/test/project/example.gdextension b/test/project/example.gdextension
index 4f599ce..fe1c92f 100644
--- a/test/project/example.gdextension
+++ b/test/project/example.gdextension
@@ -13,10 +13,10 @@ windows.debug.x86_64 = "res://bin/libgdexample.windows.template_debug.x86_64.dll
 windows.release.x86_64 = "res://bin/libgdexample.windows.template_release.x86_64.dll"
 windows.debug.arm64 = "res://bin/libgdexample.windows.template_debug.arm64.dll"
 windows.release.arm64 = "res://bin/libgdexample.windows.template_release.arm64.dll"
-linux.debug.x86_32 = "res://bin/libgdexample.linux.template_debug.x86_32.so"
-linux.release.x86_32 = "res://bin/libgdexample.linux.template_release.x86_32.so"
-linux.debug.x86_64 = "res://bin/libgdexample.linux.template_debug.x86_64.so"
-linux.release.x86_64 = "res://bin/libgdexample.linux.template_release.x86_64.so"
+linux.debug.x86_32 = "res://bin/libgdexample.linux.template_debug.dev.x86_32.so"
+linux.release.x86_32 = "res://bin/libgdexample.linux.template_release.dev.x86_32.so"
+linux.debug.x86_64 = "res://bin/libgdexample.linux.template_debug.dev.x86_64.so"
+linux.release.x86_64 = "res://bin/libgdexample.linux.template_release.dev.x86_64.so"
 linux.debug.arm32 = "res://bin/libgdexample.linux.template_debug.arm32.so"
 linux.release.arm32 = "res://bin/libgdexample.linux.template_release.arm32.so"
 linux.debug.arm64 = "res://bin/libgdexample.linux.template_debug.arm64.so"
diff --git a/test/project/project.godot b/test/project/project.godot
index 4f51c07..df3dd70 100644
--- a/test/project/project.godot
+++ b/test/project/project.godot
@@ -12,7 +12,7 @@ config_version=5
 
 config/name="GDExtension Test Project"
 run/main_scene="res://main.tscn"
-config/features=PackedStringArray("4.2")
+config/features=PackedStringArray("4.3")
 config/icon="res://icon.png"
 
 [native_extensions]
diff --git a/test/src/example.cpp b/test/src/example.cpp
index 3ec8bca..89e5d12 100644
--- a/test/src/example.cpp
+++ b/test/src/example.cpp
@@ -11,6 +11,7 @@
 #include <godot_cpp/classes/label.hpp>
 #include <godot_cpp/classes/multiplayer_api.hpp>
 #include <godot_cpp/classes/multiplayer_peer.hpp>
+#include <godot_cpp/classes/time.hpp>
 #include <godot_cpp/variant/utility_functions.hpp>
 
 using namespace godot;
@@ -297,6 +298,8 @@ Example::~Example() {
 
 // Methods.
 void Example::simple_func() {
+	int time = Time::get_singleton()->get_ticks_msec();
+	printf("time: %d\n", time);
 	emit_custom_signal("simple_func", 3);
 }
 
```

I'll open an issue on godot-cpp.

Feel free to close this as an upstream bug, unless you want to work it around downstream to avoid the crash.

**Comment by YuriSizov** [comment]
Thanks for the report!

Yeah, it's well known at this point, but having an official issue on this here is a good thing. I'll keep it open as a reminder, because indeed I may have to work around it on GDSiON's end using mihe's suggestion. I'll just transfer this to the GDSiON repo, since there is nothing that can be done in Bosca Ceoil's code.
